name = "app"
version = "1.0.0"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.1 and < 3.0.0"

[tools.lustre.html]
title = "関数型まつり2026"
lang = "ja"
links = [
    # https://coliss.com/articles/build-websites/operation/work/how-to-favicon.html#h201
    { rel= "icon", href= "/favicon.ico", "sizes"= "32x32" },
    { rel= "icon", href= "/icon.svg", "type"= "image/svg+xml" },
]
